schema_version = 1
id = "nerv-icons"
name = "Nerv Icons"
version = "1.0.3"
description = "Nerv Icons â€” Elegant icon theme for Zed"
authors = ["meastblue"]
repository = "https://github.com/meastblue/nerv-icons"

[theme]
name = "Nerv Icons"
path = "icon_themes/nerv-icons.json"
appearance = "dark"
